// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/service.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cfe9d47cff7d8cb, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type GetListUserResponse struct {
	User                 []*User  `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListUserResponse) Reset()         { *m = GetListUserResponse{} }
func (m *GetListUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetListUserResponse) ProtoMessage()    {}
func (*GetListUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cfe9d47cff7d8cb, []int{1}
}

func (m *GetListUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListUserResponse.Unmarshal(m, b)
}
func (m *GetListUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListUserResponse.Marshal(b, m, deterministic)
}
func (m *GetListUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListUserResponse.Merge(m, src)
}
func (m *GetListUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetListUserResponse.Size(m)
}
func (m *GetListUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListUserResponse proto.InternalMessageInfo

func (m *GetListUserResponse) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Age                  int64    `protobuf:"varint,2,opt,name=Age,proto3" json:"Age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cfe9d47cff7d8cb, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type AddUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cfe9d47cff7d8cb, []int{3}
}

func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResponse.Unmarshal(m, b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
}
func (m *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(m, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserResponse.Size(m)
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

func (m *AddUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "protobuf.EmptyRequest")
	proto.RegisterType((*GetListUserResponse)(nil), "protobuf.GetListUserResponse")
	proto.RegisterType((*User)(nil), "protobuf.User")
	proto.RegisterType((*AddUserResponse)(nil), "protobuf.AddUserResponse")
}

func init() { proto.RegisterFile("protobuf/service.proto", fileDescriptor_5cfe9d47cff7d8cb) }

var fileDescriptor_5cfe9d47cff7d8cb = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0x0b, 0x08,
	0x71, 0xc0, 0xc4, 0x95, 0xf8, 0xb8, 0x78, 0x5c, 0x73, 0x0b, 0x4a, 0x2a, 0x83, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x94, 0x2c, 0xb9, 0x84, 0xdd, 0x53, 0x4b, 0x7c, 0x32, 0x8b, 0x4b, 0x42, 0x8b,
	0x53, 0x8b, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x94, 0xb8, 0x58, 0x4a, 0x8b,
	0x53, 0x8b, 0x24, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0xf8, 0xf4, 0x60, 0xfa, 0xf5, 0xc0, 0xaa,
	0xc0, 0x72, 0x4a, 0x3a, 0x5c, 0x2c, 0x20, 0x9e, 0x90, 0x10, 0x17, 0x8b, 0x5f, 0x62, 0x6e, 0xaa,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0x24, 0xc0, 0xc5, 0xec, 0x98, 0x9e, 0x2a,
	0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0x62, 0x2a, 0x69, 0x73, 0xf1, 0x3b, 0xa6, 0xa4, 0xa0,
	0x58, 0x22, 0xc1, 0xc5, 0xee, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x0e, 0xd3, 0x0b, 0xe3, 0x1a, 0x75,
	0x31, 0x72, 0x71, 0x83, 0x94, 0x06, 0x43, 0x7c, 0x21, 0xe4, 0xca, 0xc5, 0x83, 0xe4, 0xca, 0x62,
	0x21, 0x31, 0x84, 0x83, 0x90, 0x7d, 0x23, 0x25, 0x8b, 0x10, 0xc7, 0xe6, 0x2b, 0x13, 0x2e, 0x76,
	0xa8, 0x1b, 0x84, 0xd0, 0xbc, 0x24, 0x25, 0x89, 0xe0, 0xa3, 0x39, 0x33, 0x89, 0x0d, 0x2c, 0x63,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x82, 0xb4, 0x1e, 0x5d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	GetListUsers(ctx context.Context, in *EmptyRequest, opts ...client.CallOption) (*GetListUserResponse, error)
	AddUser(ctx context.Context, in *User, opts ...client.CallOption) (*AddUserResponse, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "protobuf"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) GetListUsers(ctx context.Context, in *EmptyRequest, opts ...client.CallOption) (*GetListUserResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.GetListUsers", in)
	out := new(GetListUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddUser(ctx context.Context, in *User, opts ...client.CallOption) (*AddUserResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.AddUser", in)
	out := new(AddUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	GetListUsers(context.Context, *EmptyRequest, *GetListUserResponse) error
	AddUser(context.Context, *User, *AddUserResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) GetListUsers(ctx context.Context, in *EmptyRequest, out *GetListUserResponse) error {
	return h.UserServiceHandler.GetListUsers(ctx, in, out)
}

func (h *UserService) AddUser(ctx context.Context, in *User, out *AddUserResponse) error {
	return h.UserServiceHandler.AddUser(ctx, in, out)
}
